### ISSUE TITLE
Options must be strings error

### ISSUE THREAD

**Issue by DavidRWebb** [jjorissen52/tangier_api#1]
I'm having difficulty getting past an error when validating the items in the config file.  I keep getting the 'option values must be strings' error.  I'm guessing this is my error and not a real bug.  But the environment variable is set correctly and the correct file is being opened, so I'm at a loss as to what to try next.  Any help would be appreciated.   dwebb@soundphysicians.com
[... file removed ...]

**Comment by jjorissen52** [comment]
(I think you left some sensitive information in that file you uploaded, so I've gone ahead and removed it for you.) 

When I try to initialize a `LocationConnection` object with your settings, it seems to working fine, so I don't think there's anything wrong with your configuration. Could you show me a full stack trace? If you are getting something like the below, chances are it isn't finding your config file at the specified path.
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-154d0ebe2976> in <module>
----> 1 lconn = LocationConnection()
      2 pconn = ProviderConnection()
      3 lconn = ScheduleConnection()

~/.pyenv/versions/tangier-api/lib/python3.6/site-packages/tangier_api/api/location.py in __init__(self, xml_string, endpoint, show_xml_request, show_xml_response)
     23         self.show_xml_request = show_xml_request
     24         self.show_xml_response = show_xml_response
---> 25         self.base_xml = xmlmanip.inject_tags(self.base_xml, admin_user=settings.TANGIER_USERNAME, admin_pwd=settings.TANGIER_PASSWORD)
     26         self.client = zeep.Client(endpoint, transport=zeep.transports.Transport(session=requests.Session()))
     27 

~/.pyenv/versions/tangier-api/lib/python3.6/site-packages/xmlmanip.py in inject_tags(schema, parent_tag, injection_index, creative, **tags)
    328                 # raise TypeError(f"Passed kwarg '{kword} is {type(tags[kword])}. Must be str or dict.'")
    329                 raise TypeError("Passed kwarg '{kword} is {kword_type}. Must be str or dict.'".format(kword=kword,
--> 330                                                                                                       kword_type=type(tags[kword])))
    331             new_tag.text = text
    332             parent.insert(injection_index, new_tag)

TypeError: Passed kwarg 'admin_user is <class 'NoneType'>. Must be str or dict.'
```

Make sure your environment variable for setting the conf file location is either using forward slashes or double backslashes, and make sure you are importing the API library after that variable is set.

```
import os 

os.environ['TANGIER_CONF_FILE'] = "c:\\Tangier_api.txt"
# or
os.environ['TANGIER_CONF_FILE'] = "c:/Tangier_api.txt"

from tangier_api import ScheduleConnection
```

**Comment by DavidRWebb** [comment]
Thanks for your help on this.  I know you have better things to do than hand-hold a python newbie.


C:\Users\dwebb>python c:\sqlscripts\schedulemaster\tangier_python_web_service_call.py
Traceback (most recent call last):
  File "c:\sqlscripts\schedulemaster\tangier_python_web_service_call.py", line 3, in <module>
    from tangier_api import settings
  File "C:\Users\dwebb\AppData\Local\Programs\Python\Python37\lib\site-packages\tangier_api\__init__.py", line 1, in <module>
    from . api import ScheduleConnection, ScheduleManipulation, ProviderConnection, \
  File "C:\Users\dwebb\AppData\Local\Programs\Python\Python37\lib\site-packages\tangier_api\api\__init__.py", line 1, in <module>
    from .schedule import ScheduleConnection
  File "C:\Users\dwebb\AppData\Local\Programs\Python\Python37\lib\site-packages\tangier_api\api\schedule.py", line 10, in <module>
    from tangier_api import settings
  File "C:\Users\dwebb\AppData\Local\Programs\Python\Python37\lib\site-packages\tangier_api\settings.py", line 41, in <module>
    config_dict = read_config(DEFAULTS.keys())
  File "C:\Users\dwebb\AppData\Local\Programs\Python\Python37\lib\site-packages\tangier_api\settings.py", line 31, in read_config
    config = configparser.ConfigParser(defaults=DEFAULTS)
  File "C:\Users\dwebb\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 638, in __init__
    self._read_defaults(defaults)
  File "C:\Users\dwebb\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 1219, in _read_defaults
    self.read_dict({self.default_section: defaults})
  File "C:\Users\dwebb\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 755, in read_dict
    self.set(section, key, value)
  File "C:\Users\dwebb\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 1200, in set
    self._validate_value_types(option=option, value=value)
  File "C:\Users\dwebb\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 1185, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings

C:\Users\dwebb>

**Comment by jjorissen52** [comment]
I don't mind helping you out :) 

This appears to be a bug with configparser in current release of python 3.7. I just tried it with python 3.7.2 and they've identified a fix but the bug is still there.  

https://github.com/ralphbean/bugwarrior/issues/597

I believe I can implement a fix in the library, but I won't be able to release it until later. For now, is it possible you use python 3.6 ?

**Comment by DavidRWebb** [comment]
Yes, I can do that.  Thanks!

**Comment by DavidRWebb** [comment]
I switched to 3.6 but I’m still having an issue when trying to work the examples:

[cid:image002.png@01D4D8B9.F68CF7D0]

From: David Webb
Sent: Friday, February 15, 2019 7:37 AM
To: 'jjorissen52/tangier_api' <reply@reply.github.com>; jjorissen52/tangier_api <tangier_api@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [External] Re: [jjorissen52/tangier_api] Options must be strings error (#1)

Thanks for your help on this.  I know you have better things to do than hand-hold a python newbie.


C:\Users\dwebb>python c:\sqlscripts\schedulemaster\tangier_python_web_service_call.py
Traceback (most recent call last):
  File "c:\sqlscripts\schedulemaster\tangier_python_web_service_call.py", line 3, in <module>
    from tangier_api import settings
  File "C:\Users\dwebb\AppData\Local\Programs\Python\Python37\lib\site-packages\tangier_api\__init__.py", line 1, in <module>
    from . api import ScheduleConnection, ScheduleManipulation, ProviderConnection, \
  File "C:\Users\dwebb\AppData\Local\Programs\Python\Python37\lib\site-packages\tangier_api\api\__init__.py", line 1, in <module>
    from .schedule import ScheduleConnection
  File "C:\Users\dwebb\AppData\Local\Programs\Python\Python37\lib\site-packages\tangier_api\api\schedule.py", line 10, in <module>
    from tangier_api import settings
  File "C:\Users\dwebb\AppData\Local\Programs\Python\Python37\lib\site-packages\tangier_api\settings.py", line 41, in <module>
    config_dict = read_config(DEFAULTS.keys())
  File "C:\Users\dwebb\AppData\Local\Programs\Python\Python37\lib\site-packages\tangier_api\settings.py", line 31, in read_config
    config = configparser.ConfigParser(defaults=DEFAULTS)
  File "C:\Users\dwebb\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 638, in __init__
    self._read_defaults(defaults)
  File "C:\Users\dwebb\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 1219, in _read_defaults
    self.read_dict({self.default_section: defaults})
  File "C:\Users\dwebb\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 755, in read_dict
    self.set(section, key, value)
  File "C:\Users\dwebb\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 1200, in set
    self._validate_value_types(option=option, value=value)
  File "C:\Users\dwebb\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 1185, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings

C:\Users\dwebb>

**Comment by jjorissen52** [comment]
If you look at the paths in your traceback, you can see that you are still attempting to run this using your Python 3.7 installation (or at least, your interpreter is attempting to use packages from that installation). For example:

```
File "C:\Users\dwebb\AppData\Local\Programs\Python\Python37\lib\site-packages\tangier_api\api\__init__.py", line 1, in <module>
```

You can see `Python37` in the file path.

**Comment by DavidRWebb** [comment]
Where did you see python37 in this?
[cid:image001.png@01D4D8CB.C3653EA0]

**Comment by jjorissen52** [comment]
Sorry about that, I saw it in the summary of one of your previous emails. I'm viewing this conversation through Github so I didn't realize what I was seeing. Maybe it would be easier to do a video conference or something to flesh this out.

**Comment by DavidRWebb** [comment]
OK, I can send a GTM if you let me know when it would be convenient for you.

**Comment by jjorissen52** [comment]
I should be available at about 5 PM my time (3 your time, I believe). Please email me directly at jjorissen52@gmail.com .

**Comment by jjorissen52** [comment]
The original issue and the [new issue](https://github.com/jjorissen52/tangier_api/issues/3) was addressed in https://github.com/jjorissen52/tangier_api/pull/2. Can you please update your local version of the package to `tangier-api-1.2.3.dev0` and let me know that the issue has been resolved? If you need help with this step, you can reach out to me via email again.

**Comment by DavidRWebb** [comment]
Doesn’t look like it helped.
[cid:image001.png@01D4D8F3.2BA4CC20]

**Comment by jjorissen52** [comment]
Contacted via email; this issue seems to be fixed.
